In [ ]:
# Load features and labels
import pickle
fetauresPath='/content/drive/MyDrive/FeaturesEngineering/'
X = pickle.load( open( fetauresPath+"features_vgg16", "rb" ) )
y =pickle.load( open( fetauresPath+"labels", "rb" ) )

import numpy as np
print(np.array(X).shape, np.array(y).shape)

(490, 1000) (490,)


In [ ]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
import time

SVM = svm.SVC(kernel='rbf',C=100,gamma = 0.01)
def classify(X,y):
    start = time.time()
    x_train,x_test,y_train,y_test = train_test_split(np.array(X), np.array(y),test_size=0.2)
    SVM.fit(x_train,y_train)
    SVM.predict(x_test)
    score = cross_val_score(SVM, X, y, cv=2, scoring='accuracy')
    return score,time.time()-start


In [ ]:
score,tim = classify(X,y)


In [ ]:
print('accuracy :  ',score[0])
print('time :  ',tim,' secondes')

accuracy :   0.9673469387755103
time :   0.059758901596069336  secondes


<h2>Standarization: z-score normalization

---

z=(X-µ)/σ

In [ ]:
X = np.array(X)
y = np.array(y)

mu = np.mean(X)
ecrt = np.std(X)

"""Standarization
Standardize features by removing the mean and scaling to unit variance.
z = (x - u) / s
where u is the mean of the training samples or zero if with_mean=False
s is the standard deviation of the training samples or one if with_std=False.
"""
# Xzscore est la matrice de caractéristiques après standardisation
Xzscore=(X-mu)/ecrt
#print(np.array(Xzscore).shape)
zscore,time =  classify(Xzscore,y)

In [ ]:
print('accuracy :  ',zscore[0])
print('time :  ',tim,' secondes')

accuracy :   0.9551020408163265
time :   0.059758901596069336  secondes


<h2>Normalization: min-max normalization

In [ ]:
Xmin = np.min(X)
Xmax = np.max(X)
"""Noramlization
Xnorm=(X-Xmin)/(Xmax -Xmin).
"""
# Xminmax est la matrice de caractéristiques après normalisation
Xminmax= (X-Xmin)/(Xmax - Xmin)

#print(np.array(Xminmax).shape)
nscore,time =  classify(Xminmax,y)

In [ ]:
print('accuracy :  ',nscore[0])
print('time :  ',tim,' secondes')

accuracy :   0.9673469387755103
time :   0.059758901596069336  secondes


<h2>Transformation logarithmique

In [ ]:

# Transformation logarithmique
# Xlog est la matrice de caractéristiques après transformation logarithmique
Xlog= np.abs(np.log(X))
# Classification utilisant les caractéristiques aprés tranformation logarithmiq
classify(Xlog,y)

(array([0.81632653, 0.81632653]), 0.2380809783935547)

In [ ]:
XminL = np.min(Xlog)
XmaxL = np.max(Xlog)
# Normalization aprés TL
Xminmax_Log= (Xlog - XminL)/(XmaxL - XminL) 

classify(Xminmax_Log,y)

(array([0.99183673, 0.99183673]), 0.06967759132385254)

In [ ]:
# Standarization + TL
# la moyen de x
mu = np.mean(Xlog)
# l'equar type de x
s = np.std(Xlog)
# Xzscore est la matrice de caractéristiques après standardisation
Xzscore_Log=(Xlog - mu)/s
classify(Xzscore_Log,y)

(array([0.96734694, 0.98367347]), 0.2842569351196289)

<h1>Sélection de caractéristiques (features selection)



---
<h2>Suppression des caractéristiques à faible variance


In [ ]:
# Nous allons utiliser les caractéristiques après normalisation Min-Max
# Xvth est la matrice de caractéristiques après suppression des caractéristiques (après normalisation Min-Max)  à faible variance
from sklearn.feature_selection import VarianceThreshold
sp = VarianceThreshold() 
Xvth=sp.fit_transform(Xzscore_Log)
classify(Xvth,y)

(array([0.96734694, 0.98367347]), 0.3474729061126709)

<h2>chi2

In [ ]:
from sklearn.feature_selection import chi2,SelectKBest
#Xchi2 est la matrice de caractéristiques après sélection de 100 caractéristiques utilisant chi2
chi2_cara = SelectKBest(chi2, k = 100)
Xchi2 = chi2_cara.fit_transform(X, y)
classify(Xchi2,y)

(array([0.96734694, 0.96326531]), 0.047460079193115234)